### ISSUE TITLE
Please delte the SourceCode from [mc-nexus.de]

### ISSUE THREAD

**Issue by NightlandDriver** [DeSireFire/webExampleRepo#1]
This source code of the website has been illegally downloaded and published here without consent.
The website is owned by Mc-Nexus.de and the developer ThegreenY.

If the files are not removed I have to report this violation to Github and take legal action.

**Comment by DeSireFire** [comment]
I'm sorry for this matter and  The file has been deleted.

**Comment by NightlandDriver** [comment]
Vielen Dank für die schnelle Lösung
